# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "be-dev" ]
  pull_request:
    branches: [ "be-dev" ]

permissions:
  contents: read

defaults:
  run:
    working-directory: server

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      ## JDK setting

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: be-dev
          repository: yelm-212/seb44_main_017_test

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Set permission for gradlew
        run: chmod +x ./gradlew

      ## Gradle Build without test
      - name: Build with Gradle
        run: ./gradlew clean build -x test

      ## Docker with Docker Setup Buildx

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      ## push to docker hub
      - name: web docker build and push with docker action
        uses: docker/build-push-action@v1
        with:
          dockerfile: ./server/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          path: server
          push: true
          repository: 21yrshin/seb44_main_017
          tags: latest

      ## docker compose up
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          script: |
            sudo docker rm -f spring
            sudo docker pull 21yrshin/seb44_main_017:latest
            sudo docker-compose up -d
            docker image prune -f